project_id = "mppaccncoezmlvizmifu"

[functions.telegram-webhook]
verify_jwt = false

[functions.get-download-link]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false
