# Cloudflare Pages Configuration

# This file is used to configure deployment to Cloudflare Pages.

[build]
# The build command that will be executed during deployment.
command = "npm run build"

[assets]
# The directory where the build output will be located.
directory = "./dist"